### ISSUE TITLE
suggestion and help

### ISSUE THREAD

**Issue by chufo4** [majdsassi/Pico-WIFI-Duck#1]
how can i add a keylogger into this?

**Comment by majdsassi** [comment]
You can check out this thread [HERE](https://forums.hak5.org/topic/40066-powershell-keylogger-in-seconds/?do=findComment&comment=287096), and I'll add some built-in scripts that will run with a press of a button, so stay updated

**Comment by chufo4** [comment]
thank you very much thou i need some help with a keyboard layout issue in https://github.com/majdsassi/Pico-WIFI-Duck/issues/2
